name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8d0de2f13a892f78bdfafe757621c04a786a4a5a751de3dbc26baa79e3b3525"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
