name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98d3352a6f38015f6683e7e3c7e8cf00842ee9ea2db4ca39c8e33d66595f9be0"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-directory = "datapacks"
