name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "796d429d2682e1fd1875d7cb227bbb6b1f488a856c487d9a1384ae5c82cb44a4"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
