name = "Commandless"
author = "codeNredstone"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0730dd9038f18253280ddf6dc1b237dfaf288dea1e951ec64f3bf08af5f86ab"

[versions]
fabric = "0.18.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
datapack-directory = "datapacks"
